spring.application.name=user-service

server.port=8081
server.address= 0.0.0.0

spring.datasource.url=jdbc:postgresql://localhost:5432/unidelivery_user_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.change-log=classpath:db/changelog/changelog-master.xml
spring.liquibase.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/unidelivery
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9090/realms/unidelivery/protocol/openid-connect/certs

spring.security.oauth2.client.registration.keycloak.client-id=user-service
spring.security.oauth2.client.registration.keycloak.client-secret=ZcqFQdvl0TtN1rhaXorktp3oMZhZxmuq
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

keycloak.keycloak-server-url=http://localhost:9090
keycloak.realm=unidelivery
keycloak.client-id=user-service
keycloak.client-secret=ZcqFQdvl0TtN1rhaXorktp3oMZhZxmuq
keycloak.admin-username=admin
keycloak.admin-password=admin


spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9090/realms/unidelivery
spring.security.oauth2.client.provider.keycloak.authorization-uri=http://localhost:9090/realms/unidelivery/protocol/openid-connect/auth
spring.security.oauth2.client.provider.keycloak.token-uri=http://localhost:9090/realms/unidelivery/protocol/openid-connect/token
spring.security.oauth2.client.provider.keycloak.user-info-uri=http://localhost:9090/realms/unidelivery/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.keycloak.jwk-set-uri=http://localhost:9090/realms/unidelivery/protocol/openid-connect/certs
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${server.port}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

logging.level.com.unidelivery.user=DEBUG
logging.level.org.springframework.security=DEBUG